In [14]:
import pandas as pd
data = {"aname": ["Sumit","Rahul", "Ankit"],
        "Age": [21, 23, 25],
        "salary": [2400, 3400, 540]
       }
df = pd.DataFrame(data)
print(df)

   aname  Age  salary
0  Sumit   21    2400
1  Rahul   23    3400
2  Ankit   25     540

In [48]:
df = pd.read_csv("C:\\Users\\hp\\OneDrive\\Desktop\\apple_products.csv")
df

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         62 non-null     object
 1   Product URL          62 non-null     object
 2   Brand                62 non-null     object
 3   Sale Price           62 non-null     int64
 4   Mrp                  62 non-null     int64
 5   Discount Percentage  62 non-null     int64
 6   Number Of Ratings    62 non-null     int64
 7   Number Of Reviews    62 non-null     int64
 8   Upc                  62 non-null     object
 9   Star Rating          62 non-null     float64
 10  Star Rating.1        62 non-null     float64
dtypes: float64(2), int64(5), object(4)
memory usage: 5.5+ KB

In [26]:
df.describe()

        Age       salary
count   3.0     3.000000
mean   23.0  2113.333333
std     2.0  1451.390138
min    21.0   540.000000
25%    22.0  1470.000000
50%    23.0  2400.000000
75%    24.0  2900.000000
max    25.0  3400.000000

In [58]:
df_new = df[['Product Name', 'Sale Price', 'Discount Percentage']]
df_new

                                Product Name  Sale Price  Discount Percentage
0          APPLE iPhone 8 Plus (Gold, 64 GB)       49900                    0
1   APPLE iPhone 8 Plus (Space Grey, 256 GB)       84900                    0
2       APPLE iPhone 8 Plus (Silver, 256 GB)       84900                    0
3            APPLE iPhone 8 (Silver, 256 GB)       77000                    0
4              APPLE iPhone 8 (Gold, 256 GB)       77000                    0
..                                       ...         ...                  ...
57            APPLE iPhone SE (Black, 64 GB)       29999                   24
58           APPLE iPhone 11 (Purple, 64 GB)       46999                   14
59            APPLE iPhone 11 (White, 64 GB)       46999                   14
60            APPLE iPhone 11 (Black, 64 GB)       46999                   14
61              APPLE iPhone 11 (Red, 64 GB)       46999                   14

[62 rows x 3 columns]

In [38]:
type(df)

pandas.core.frame.DataFrame

In [60]:
df.iloc[3:]

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
5,"APPLE iPhone 8 Plus (Silver, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGVQGYYP8FV,4.6,5.6
6,"APPLE iPhone 8 Plus (Space Grey, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGVQKBREZP8,4.6,5.6
7,"APPLE iPhone 8 (Space Grey, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVZFZGZEWV,4.5,5.5
8,"APPLE iPhone XS Max (Silver, 64 GB)",Product URL,Apple,89900,89900,0,1454,149,MOBF944E2XAHW8V5,4.6,5.6
9,"Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...",Product URL,Apple,41999,52900,20,79512,6796,MOBF9Z7ZHQC23PWQ,4.6,5.6
10,"Apple iPhone XR (Black, 64 GB) (Includes EarPo...",Product URL,Apple,39999,47900,16,79512,6796,MOBF9Z7ZPHGV4GNH,4.6,5.6
11,"Apple iPhone XR (Coral, 128 GB) (Includes EarP...",Product URL,Apple,41999,52900,20,79582,6804,MOBF9Z7ZS6GF5UAP,4.6,5.6
12,"Apple iPhone XR (Black, 128 GB) (Includes EarP...",Product URL,Apple,41999,52900,20,79512,6796,MOBF9Z7ZYWNFGZUC,4.6,5.6
13,"Apple iPhone XR (White, 128 GB) (Includes EarP...",Product URL,Apple,41999,52900,20,79512,6796,MOBF9Z7ZZY3HCDZZ,4.6,5.6
14,"APPLE iPhone 11 Pro Max (Gold, 256 GB)",Product URL,Apple,131900,131900,0,1078,101,MOBFKCTS7HCHSPFH,4.7,5.7
15,"APPLE iPhone 11 Pro Max (Gold, 64 GB)",Product URL,Apple,117100,117100,0,1078,101,MOBFKCTSAPAYNSGG,4.7,5.7
16,"APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)",Product URL,Apple,131900,131900,0,1078,101,MOBFKCTSCAAKGQV7,4.7,5.7
17,"APPLE iPhone 11 Pro Max (Space Grey, 64 GB)",Product URL,Apple,117100,117100,0,1078,101,MOBFKCTSKDMKCGQS,4.7,5.7
18,"APPLE iPhone 11 Pro (Midnight Green, 64 GB)",Product URL,Apple,74999,106600,29,7088,523,MOBFKCTSN3TG3RFJ,4.6,5.6
19,"APPLE iPhone 11 Pro (Space Grey, 512 GB)",Product URL,Apple,117900,140300,15,7088,523,MOBFKCTSRTHRQTFT,4.6,5.6
20,"APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)",Product URL,Apple,117100,117100,0,1078,101,MOBFKCTSRYPAQNYT,4.7,5.7
21,"APPLE iPhone 11 Pro (Midnight Green, 512 GB)",Product URL,Apple,117900,140300,15,7088,523,MOBFKCTSSJCWYGCC,4.6,5.6
22,"APPLE iPhone 11 Pro (Space Grey, 256 GB)",Product URL,Apple,99900,121300,17,7081,522,MOBFKCTSWGYSAS9X,4.6,5.6
23,"Apple iPhone SE (White, 256 GB) (Includes EarP...",Product URL,Apple,44999,54900,18,95909,8161,MOBFRFXHPZCHAPEH,4.5,5.5
24,"APPLE iPhone 12 Pro (Silver, 512 GB)",Product URL,Apple,140900,149900,6,542,42,MOBFWBYZ5UY6ZBVA,4.5,5.5
25,"APPLE iPhone 12 Pro Max (Pacific Blue, 256 GB)",Product URL,Apple,130900,139900,6,580,45,MOBFWBYZ8STJXCVT,4.6,5.6
26,"APPLE iPhone 12 Mini (White, 128 GB)",Product URL,Apple,64900,74900,13,740,64,MOBFWBYZAGXJRDGB,4.5,5.5
27,"APPLE iPhone 12 Pro (Graphite, 256 GB)",Product URL,Apple,120900,129900,6,545,42,MOBFWBYZBA36UB7G,4.5,5.5
28,"APPLE iPhone 12 Mini (White, 64 GB)",Product URL,Apple,59900,69900,14,740,64,MOBFWBYZBH4CEC4C,4.5,5.5
29,"APPLE iPhone 12 (White, 128 GB)",Product URL,Apple,75900,84900,10,2101,180,MOBFWBYZBTZFGJF9,4.6,5.6
30,"APPLE iPhone 12 Pro (Graphite, 128 GB)",Product URL,Apple,110900,119900,7,545,42,MOBFWBYZBZ7Y56WD,4.5,5.5
31,"APPLE iPhone 12 Pro Max (Graphite, 256 GB)",Product URL,Apple,130900,139900,6,580,45,MOBFWBYZEF6XQ5ZW,4.6,5.6
32,"APPLE iPhone 12 Pro Max (Graphite, 128 GB)",Product URL,Apple,120900,129900,6,580,45,MOBFWBYZFDGQSDWS,4.6,5.6
33,"APPLE iPhone 12 Mini (Black, 128 GB)",Product URL,Apple,64900,74900,13,730,63,MOBFWBYZH2AMPNPD,4.5,5.5
34,"APPLE iPhone 12 Mini (Blue, 128 GB)",Product URL,Apple,64900,74900,13,730,63,MOBFWBYZHU58PHCZ,4.5,5.5
35,"APPLE iPhone 12 (Black, 128 GB)",Product URL,Apple,75900,84900,10,2101,180,MOBFWBYZK3HACR72,4.6,5.6
36,"APPLE iPhone 12 (Blue, 128 GB)",Product URL,Apple,75900,84900,10,2101,180,MOBFWBYZKPTZF9VG,4.6,5.6
37,"APPLE iPhone 12 Pro Max (Silver, 128 GB)",Product URL,Apple,120900,129900,6,580,45,MOBFWBYZNSNVGGZC,4.6,5.6
38,"APPLE iPhone 12 Mini (Red, 64 GB)",Product URL,Apple,59900,69900,14,740,64,MOBFWBYZNVWGWN2U,4.5,5.5
39,"APPLE iPhone 12 Pro Max (Gold, 128 GB)",Product URL,Apple,120900,129900,6,580,45,MOBFWBYZQVKT77YH,4.6,5.6
40,"APPLE iPhone 12 (Green, 128 GB)",Product URL,Apple,75900,84900,10,2092,178,MOBFWBYZQXUEHF48,4.6,5.6
41,"APPLE iPhone 12 Pro (Pacific Blue, 512 GB)",Product URL,Apple,140900,149900,6,545,42,MOBFWBYZTHSXKMGW,4.5,5.5
42,"APPLE iPhone 12 (White, 64 GB)",Product URL,Apple,70900,79900,11,2101,180,MOBFWBYZTK33MBG9,4.6,5.6
43,"APPLE iPhone 12 (Black, 64 GB)",Product URL,Apple,70900,79900,11,2092,178,MOBFWBYZU5FWK2VP,4.6,5.6
44,"APPLE iPhone 12 (Red, 128 GB)",Product URL,Apple,75900,84900,10,2101,180,MOBFWBYZUHPFWQRD,4.6,5.6
45,"APPLE iPhone 12 Mini (Black, 64 GB)",Product URL,Apple,59900,69900,14,740,64,MOBFWBYZXSEGBS6F,4.5,5.5
46,"APPLE iPhone 12 Pro (Pacific Blue, 128 GB)",Product URL,Apple,110900,119900,7,545,42,MOBFWBYZXYSCEEEH,4.5,5.5
47,"APPLE iPhone 12 Pro Max (Pacific Blue, 128 GB)",Product URL,Apple,120900,129900,6,580,45,MOBFWBYZZABKHZQA,4.6,5.6
48,"APPLE iPhone 12 Pro Max (Silver, 256 GB)",Product URL,Apple,130900,139900,6,580,45,MOBFWBYZZH4AM8FE,4.6,5.6
49,"APPLE iPhone 12 Pro Max (Gold, 256 GB)",Product URL,Apple,130900,139900,6,580,45,MOBFWBYZZPW8JHQF,4.6,5.6
50,"APPLE iPhone 11 (White, 128 GB)",Product URL,Apple,54999,59900,8,43707,3357,MOBFWQ6B7KKRXDDS,4.6,5.6
51,"APPLE iPhone 11 (Red, 128 GB)",Product URL,Apple,54999,59900,8,43707,3357,MOBFWQ6BEZTNK59G,4.6,5.6
52,"APPLE iPhone SE (White, 64 GB)",Product URL,Apple,29999,39900,24,95807,8154,MOBFWQ6BGWDVGF3E,4.5,5.5
53,"APPLE iPhone SE (Black, 128 GB)",Product URL,Apple,34999,44900,22,95909,8161,MOBFWQ6BHUEVZPXD,4.5,5.5
54,"APPLE iPhone SE (White, 128 GB)",Product URL,Apple,34999,44900,22,95807,8154,MOBFWQ6BJEHMUUZY,4.5,5.5
55,"APPLE iPhone SE (Red, 128 GB)",Product URL,Apple,34999,44900,22,95909,8161,MOBFWQ6BJTVFKPEJ,4.5,5.5
56,"APPLE iPhone 11 (Black, 128 GB)",Product URL,Apple,54999,59900,8,43470,3331,MOBFWQ6BKRYBP5X8,4.6,5.6
57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6

In [66]:
df.iloc[[2, 5,8], 0:4]

                           Product Name  Product URL  Brand  Sale Price
2  APPLE iPhone 8 Plus (Silver, 256 GB)  Product URL  Apple       84900
5   APPLE iPhone 8 Plus (Silver, 64 GB)  Product URL  Apple       49900
8   APPLE iPhone XS Max (Silver, 64 GB)  Product URL  Apple       89900

In [72]:
df.loc[0:10, ['Product Name']]

                                         Product Name
0                   APPLE iPhone 8 Plus (Gold, 64 GB)
1            APPLE iPhone 8 Plus (Space Grey, 256 GB)
2                APPLE iPhone 8 Plus (Silver, 256 GB)
3                     APPLE iPhone 8 (Silver, 256 GB)
4                       APPLE iPhone 8 (Gold, 256 GB)
5                 APPLE iPhone 8 Plus (Silver, 64 GB)
6             APPLE iPhone 8 Plus (Space Grey, 64 GB)
7                 APPLE iPhone 8 (Space Grey, 256 GB)
8                 APPLE iPhone XS Max (Silver, 64 GB)
9   Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...
10  Apple iPhone XR (Black, 64 GB) (Includes EarPo...

In [74]:
df.reset_index()

,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6
1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...
57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6

In [78]:
df.reset_index(inplace=True)
df

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
0,0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6
1,1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
2,2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
3,3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
4,4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
58,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
59,59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
60,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
61,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6

In [96]:
df.sort_index(ascending=False,inplace=True)
df

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
61,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6
60,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
59,59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
58,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
57,57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
3,3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
2,2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
1,1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
0,0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6

In [100]:
df.sort_values(['Product Name'], ascending=[True])

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
56,56,56,"APPLE iPhone 11 (Black, 128 GB)",Product URL,Apple,54999,59900,8,43470,3331,MOBFWQ6BKRYBP5X8,4.6,5.6
60,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
58,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
51,51,51,"APPLE iPhone 11 (Red, 128 GB)",Product URL,Apple,54999,59900,8,43707,3357,MOBFWQ6BEZTNK59G,4.6,5.6
61,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,9,9,"Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...",Product URL,Apple,41999,52900,20,79512,6796,MOBF9Z7ZHQC23PWQ,4.6,5.6
12,12,12,"Apple iPhone XR (Black, 128 GB) (Includes EarP...",Product URL,Apple,41999,52900,20,79512,6796,MOBF9Z7ZYWNFGZUC,4.6,5.6
10,10,10,"Apple iPhone XR (Black, 64 GB) (Includes EarPo...",Product URL,Apple,39999,47900,16,79512,6796,MOBF9Z7ZPHGV4GNH,4.6,5.6
11,11,11,"Apple iPhone XR (Coral, 128 GB) (Includes EarP...",Product URL,Apple,41999,52900,20,79582,6804,MOBF9Z7ZS6GF5UAP,4.6,5.6
13,13,13,"Apple iPhone XR (White, 128 GB) (Includes EarP...",Product URL,Apple,41999,52900,20,79512,6796,MOBF9Z7ZZY3HCDZZ,4.6,5.6

In [104]:
df.reset_index(drop=True)

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
0,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6
1,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
2,59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
3,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
4,57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
58,3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
59,2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
60,1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
61,0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6

In [122]:
fc = df['Product Name'] == 'south'
df.loc[fc]
df

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
61,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6
60,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
59,59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
58,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
57,57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
3,3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
2,2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
1,1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
0,0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6

In [124]:
 df.loc[df['Product Name'] == 'south']
df

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
61,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6
60,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
59,59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
58,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
57,57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
3,3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
2,2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
1,1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
0,0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6

In [130]:
df.loc[(df['Product Name'] == 'south') & (df['Sale Price']>0)]

Empty DataFrame
Columns: [level_0, index, Product Name, Product URL, Brand, Sale Price, Mrp, Discount Percentage, Number Of Ratings, Number Of Reviews, Upc, Star Rating, Star Rating.1]
Index: []

In [132]:
df.loc[(df['Product Name'] == 'south') | (df['Sale Price']>0)]

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
61,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6
60,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
59,59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
58,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
57,57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
3,3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
2,2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
1,1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
0,0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6

In [136]:
df.loc[~(df['Product Name'] == 'south')]

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
61,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6
60,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
59,59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
58,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
57,57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
3,3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
2,2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
1,1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
0,0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6

In [138]:
df.drop(columns='Product Name')

,level_0,index,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1
61,61,61,Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6
60,60,60,Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6
59,59,59,Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6
58,58,58,Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6
57,57,57,Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,4,Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5
3,3,3,Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5
2,2,2,Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6
1,1,1,Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6
0,0,0,Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6

In [142]:
df['Number Of Ratings_flag'] = 1
df

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1,Number Of Ratings_flag
61,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6,1
60,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6,1
59,59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6,1
58,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6,1
57,57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5,1
3,3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5,1
2,2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6,1
1,1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6,1
0,0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6,1

In [144]:
df['Product Name'].apply(len)

61    28
60    30
59    30
58    31
57    30
      ..
4     29
3     31
2     36
1     40
0     33
Name: Product Name, Length: 62, dtype: int64

In [146]:
df['Product Name_len'] = df['Product Name'].apply(len)
df

,level_0,index,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Star Rating.1,Number Of Ratings_flag,Product Name_len
61,61,61,"APPLE iPhone 11 (Red, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,5.6,1,28
60,60,60,"APPLE iPhone 11 (Black, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,5.6,1,30
59,59,59,"APPLE iPhone 11 (White, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,5.6,1,30
58,58,58,"APPLE iPhone 11 (Purple, 64 GB)",Product URL,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,5.6,1,31
57,57,57,"APPLE iPhone SE (Black, 64 GB)",Product URL,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,5.5,1,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,4,"APPLE iPhone 8 (Gold, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,5.5,1,29
3,3,3,"APPLE iPhone 8 (Silver, 256 GB)",Product URL,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,5.5,1,31
2,2,2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,5.6,1,36
1,1,1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Product URL,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,5.6,1,40
0,0,0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Product URL,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,5.6,1,33